# Within this file we map the unintuitive cell headlines of the html website to intuitive names for our storage and analysis.

HEADER_NORMALIZATION = {
    # Name variants
    "Name": "Name",
    "Name(s)": "Name",
    "Player": "Name",
    # Team variants
    "Team": "Team",
    "Team(s)": "Team",
    "Team [Click for roster]": "Team",
    "Team | Roster": "Team",
    "Team | Roster]": "Team",
    "TEAM": "Team",
    "#": "Statistic Value",
    "Top 25": "Top 25",
    "W": "Total Wins",
    "L": "Total Loses",
    "T": "Total Ties",
    "WP": "Winning Percentage",
    "GB": "Games Behind",
    # Statistics
    "2B": "Total Doubles",
    "3B": "Total Triples",
    "AB": "Total At Bats",
    "AVG": "Batting Average",
    "BB": "Total Walks",
    "CG": "Total Complete Games",
    "CS": "Total Caught Stealings",
    "ER": "Total Earned Runs",
    "ERA": "Earned Run Average",
    "G": "Total Games",
    "H": "Total Hits",
    "HA": "Total Hits Allowed",
    "HBP": "Total Hit By Pitch",
    "HR": "Total Home Runs",
    "IP": "Total Innings Pitched",
    "OBP": "On-Base Percentage",
    "R": "Total Runs",
    "RBI": "Total Runs Batted In",
    "SB": "Total Stolen Bases",
    "SH": "Total Sacrifice Hits",
    "SHO": "Total Shutouts",
    "SLG": "Slugging Percentage",
    "SO": "Total Strikeouts",
    "SV": "Total Saves",
    "SVO": "Total Save Opportunities",

    "East" : "Division",
    "South" : "Division",
    "North" : "Division",
    "West" : "Division",
    "Central" : "Division",

    "Losses" : "Total Losses",
    "Ties" : "Total Ties",
    "Wins" : "Total Wins",
}
